services:
  - type: web
    name: live-leaderboard-api
    runtime: node
    plan: free
    buildCommand: cd server && npm ci
    startCommand: cd server && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://live-leaderboard-client.onrender.com
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: live-leaderboard-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: live-leaderboard-redis
          property: port

  - type: web
    name: live-leaderboard-client
    runtime: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://live-leaderboard-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: keyvalue
    name: live-leaderboard-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
